# .streamlit/secrets.toml

[general]
OPENAI_API_KEY = "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"
